CREATE TABLE member (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 login_id VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 phone_number VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL,
 birth DATE NOT NULL, gender VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL,
 nickname VARCHAR(255) NOT NULL, interested_region BIGINT NOT NULL
);
INSERT INTO member(login_id,password,phone_number,name,birth,gender,email,nickname,interested_region)
VALUES ('legacy-member','existing-hash','01011112222','Legacy','1990-01-01','F','legacy@example.com','Legacy',1);
